# Generated by Django 5.0.5 on 2024-05-09 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0002_alter_iteminorder_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Обозначение преимущества')),
                ('description', models.TextField(verbose_name='Описание преимущества')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
    ]
