# Generated by Django 5.0.5 on 2024-05-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0003_advantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=255, verbose_name='Описание'),
        ),
    ]
