# Generated by Django 5.0.5 on 2024-05-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0005_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=255, verbose_name='Город клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='Телефон клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('call', 'Звонок'), ('measure', 'Замер'), ('consultation', 'Консультация'), ('pick', 'Подбор')], default='', max_length=255, verbose_name='Тип заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='wishes',
            field=models.TextField(blank=True, default='', verbose_name='Пожелания'),
        ),
        migrations.DeleteModel(
            name='ItemInOrder',
        ),
    ]
