# Generated by Django 5.0.5 on 2024-05-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0006_remove_order_products_remove_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('call', 'Звонок'), ('measure', 'Замер'), ('consultation', 'Консультация'), ('pick', 'Подбор')], default='call', max_length=255, verbose_name='Тип заказа'),
        ),
    ]
