# Generated by Django 5.0.5 on 2024-05-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0007_alter_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('done', 'Выполненный'), ('canceled', 'Отмененный')], default='new', max_length=255, verbose_name='Статус'),
        ),
    ]
