# Generated by Django 5.0.5 on 2024-05-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0010_alter_productphoto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=12, verbose_name='Телефон клиента'),
        ),
    ]
